services:
  falcon-rabbitmq:
    image: rabbitmq:management
    container_name: falcon-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: falcon
      RABBITMQ_DEFAULT_PASS: falcon
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  falcon-ollama:
    image: ollama/ollama
    container_name: falcon-ollama
    tty: true
    pull_policy: always
    ports:
      - "11434:11434"
    networks:
      - app-network
    restart: unless-stopped
    entrypoint: [ "/bin/sh", "/falcon-ollama/run_ollama.sh" ]
    volumes:
      - ./ollama:/falcon-ollama
      - ./ollama/root:/root
networks:
  app-network:
    driver: bridge
    name: app-network
volumes:
  back-data:
